// Generated by pc/tools/gen_stubs.py. Do not edit: run the script again.
//
// Every function here is referenced by code in the PC build but has no
// implementation yet. A real definition anywhere else overrides its stub
// (stubs are weak); regenerating the file then drops the stub.

#include <pc/stub.h>

// ---- nw4r::ut (9) ----
PC_STUB(_ZN4nw4r2ut14NandFileStream5CloseEv, "nw4r::ut::NandFileStream::Close()")
PC_STUB(_ZN4nw4r2ut14NandFileStreamC2EPK12NANDFileInfojb, "nw4r::ut::NandFileStream::NandFileStream(NANDFileInfo const*, unsigned int, bool)")
PC_STUB(_ZN4nw4r2ut14NandFileStreamC2EPKcj, "nw4r::ut::NandFileStream::NandFileStream(char const*, unsigned int)")
PC_STUB(_ZN4nw4r2ut14NandFileStream4ReadEPvj, "nw4r::ut::NandFileStream::Read(void*, unsigned int)")
PC_STUB(_ZN4nw4r2ut14NandFileStream9ReadAsyncEPvjPFviPNS0_8IOStreamES2_ES2_, "nw4r::ut::NandFileStream::ReadAsync(void*, unsigned int, void (*)(int, nw4r::ut::IOStream*, void*), void*)")
PC_STUB(_ZN4nw4r2ut14NandFileStream4SeekEij, "nw4r::ut::NandFileStream::Seek(int, unsigned int)")
PC_STUB(_ZN4nw4r2ut14NandFileStream5WriteEPKvj, "nw4r::ut::NandFileStream::Write(void const*, unsigned int)")
PC_STUB(_ZN4nw4r2ut14NandFileStream10WriteAsyncEPKvjPFviPNS0_8IOStreamEPvES6_, "nw4r::ut::NandFileStream::WriteAsync(void const*, unsigned int, void (*)(int, nw4r::ut::IOStream*, void*), void*)")
PC_STUB(_ZN4nw4r2ut14NandFileStreamD2Ev, "nw4r::ut::NandFileStream::~NandFileStream()")
