// Generated by pc/tools/gen_stubs.py. Do not edit: run the script again.
//
// Every function here is referenced by code in the PC build but has no
// implementation yet. A real definition anywhere else overrides its stub
// (stubs are weak); regenerating the file then drops the stub.

#include <pc/stub.h>

// ---- CX (3) ----
PC_STUB(CXGetUncompressedSize, "CXGetUncompressedSize")
PC_STUB(CXInitUncompContextHuffman, "CXInitUncompContextHuffman")
PC_STUB(CXReadUncompHuffman, "CXReadUncompHuffman")

// ---- DVD (5) ----
PC_STUB(DVDCancel, "DVDCancel")
PC_STUB(DVDClose, "DVDClose")
PC_STUB(DVDFastOpen, "DVDFastOpen")
PC_STUB(DVDReadAsyncPrio, "DVDReadAsyncPrio")
PC_STUB(DVDReadPrio, "DVDReadPrio")

// ---- GX (26) ----
PC_STUB(GXBegin, "GXBegin")
PC_STUB(GXClearVtxDesc, "GXClearVtxDesc")
PC_STUB(GXInitTexObj, "GXInitTexObj")
PC_STUB(GXInitTexObjLOD, "GXInitTexObjLOD")
PC_STUB(GXLoadTexObj, "GXLoadTexObj")
PC_STUB(GXSetBlendMode, "GXSetBlendMode")
PC_STUB(GXSetChanCtrl, "GXSetChanCtrl")
PC_STUB(GXSetFog, "GXSetFog")
PC_STUB(GXSetNumChans, "GXSetNumChans")
PC_STUB(GXSetNumIndStages, "GXSetNumIndStages")
PC_STUB(GXSetNumTevStages, "GXSetNumTevStages")
PC_STUB(GXSetNumTexGens, "GXSetNumTexGens")
PC_STUB(GXSetTevAlphaIn, "GXSetTevAlphaIn")
PC_STUB(GXSetTevAlphaOp, "GXSetTevAlphaOp")
PC_STUB(GXSetTevColor, "GXSetTevColor")
PC_STUB(GXSetTevColorIn, "GXSetTevColorIn")
PC_STUB(GXSetTevColorOp, "GXSetTevColorOp")
PC_STUB(GXSetTevDirect, "GXSetTevDirect")
PC_STUB(GXSetTevOp, "GXSetTevOp")
PC_STUB(GXSetTevOrder, "GXSetTevOrder")
PC_STUB(GXSetTevSwapMode, "GXSetTevSwapMode")
PC_STUB(GXSetTevSwapModeTable, "GXSetTevSwapModeTable")
PC_STUB(GXSetTexCoordGen2, "GXSetTexCoordGen2")
PC_STUB(GXSetVtxAttrFmt, "GXSetVtxAttrFmt")
PC_STUB(GXSetVtxDesc, "GXSetVtxDesc")
PC_STUB(GXSetZTexture, "GXSetZTexture")

// ---- MTX (4) ----
PC_STUB(PSMTXConcat, "PSMTXConcat")
PC_STUB(PSMTXRotAxisRad, "PSMTXRotAxisRad")
PC_STUB(PSMTXRotRad, "PSMTXRotRad")
PC_STUB(PSMTXTrans, "PSMTXTrans")

// ---- NET (1) ----
PC_STUB(NETGetUniversalCalendar, "NETGetUniversalCalendar")

// ---- OS (17) ----
PC_STUB(DCFlushRange, "DCFlushRange")
PC_STUB(LCDisable, "LCDisable")
PC_STUB(LCEnable, "LCEnable")
PC_STUB(LCLoadBlocks, "LCLoadBlocks")
PC_STUB(LCQueueLength, "LCQueueLength")
PC_STUB(LCStoreBlocks, "LCStoreBlocks")
PC_STUB(LCStoreData, "LCStoreData")
PC_STUB(OSDisableInterrupts, "OSDisableInterrupts")
PC_STUB(OSGetFontEncode, "OSGetFontEncode")
PC_STUB(OSGetFontTexture, "OSGetFontTexture")
PC_STUB(OSGetFontWidth, "OSGetFontWidth")
PC_STUB(OSInitFont, "OSInitFont")
PC_STUB(OSInitMutex, "OSInitMutex")
PC_STUB(OSLockMutex, "OSLockMutex")
PC_STUB(OSRestoreInterrupts, "OSRestoreInterrupts")
PC_STUB(OSUnlockMutex, "OSUnlockMutex")
PC_STUB(OSYieldThread, "OSYieldThread")

// ---- SC (2) ----
PC_STUB(SCGetLanguage, "SCGetLanguage")
PC_STUB(SCGetProductArea, "SCGetProductArea")

// ---- undeclared (1) ----
PC_STUB(DVDCancelAsync, "DVDCancelAsync")

// ---- variables defined in files that are not in the build yet (4) ----
// Zero-filled, sized from config/HAGE/symbols.txt.
PC_STUB_DATA(gCursorX, 0x100)
PC_STUB_DATA(gCursorY, 0x100)
PC_STUB_DATA(gKPADLatest, 0x10)
PC_STUB_DATA(gPointerValid, 0x40)
